name: deploy-environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      secret_string:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Count the number of characters in the input and secret string and print to the console.
      - name: Count characters
        run: |
          secret="${{ secrets.secret_string }}"
          length=${#secret}
          echo "Secret string length: $length"
