# .github/workflows/deploy.yml
name: deploy

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - ".deploy/test"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Always deploy on a release event.
    # On push to .deploy/test, skip if the commit is a Release Please merge.
    if: |
      github.event_name == 'release' ||
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'chore(main): release'))
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy app
        run: ./scripts/deploy.sh
