name: Notify Slack on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  notify-slack-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification for merged PR
        env:
          SLACK_WEBHOOK: ${{ secrets.GC_SIGNIN_OPS_SLACK_INFO_WEBHOOK }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REPO_NAME: ${{ github.repository }}
        run: |
          json=$(jq -n \
            --arg title "$PR_TITLE" \
            --arg author "$PR_AUTHOR" \
            --arg url "$PR_URL" \
            --arg repo "$REPO_NAME" \
            '{
              text: ":tada: A pull request has been merged!",
              attachments: [
                {
                  color: "#36a64f",
                  fields: [
                    { title: "Repository", value: $repo, short: true },
                    { title: "Author", value: $author, short: true },
                    { title: "Title", value: $title, short: false },
                    { title: "Link", value: "<\($url)|View Pull Request>", short: false }
                  ]
                }
              ]
            }')
          echo "$json"
