on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-pipeline

# Run release-please and build-application in parallel,
# then run deploy-environment in both dev and test environments.

jobs:
  release-please:
    uses: ./.github/workflows/release-please.yml

  build-application:
    uses: ./.github/workflows/build-application.yml
    secrets: inherit

  deploy:
    needs: [release-please, build-application]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [test, staging, production]

    # This attaches the job to the corresponding GitHub environment
    environment: ${{ matrix.env }}

    steps:
      - uses: ./.github/workflows/deploy-environment.yml
        secrets: inherit
