on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple

      # Check out the PR branch only if a release PR was created or updated
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        with:
          ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}

      # Update the file with the commit SHA of the release
      - name: Update .deploy/test with release commit SHA
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        run: |
          echo "${{ steps.release.outputs.sha }}" > .deploy/test
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .deploy/test
          git commit -m "chore: update .deploy/test with release commit SHA"
          git push
